# Generated by Django 5.2.6 on 2025-09-21 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_studentprofile_aadhaar_number_studentprofile_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll_no', models.CharField(max_length=20)),
                ('university_reg_no', models.CharField(max_length=20)),
                ('admission_no', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=10)),
                ('birth_date', models.DateField()),
                ('address', models.TextField()),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=15)),
                ('cgpa', models.DecimalField(decimal_places=2, max_digits=4)),
                ('sslc_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('puc_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
