# Generated by Django 5.2.6 on 2025-09-21 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
