# Generated by Django 5.2.6 on 2025-09-21 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_studentprofile_admission_no_studentprofile_cgpa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='caste',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='signature',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='student_phone',
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='aadhaar_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='semester',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
