# Generated by Django 5.2.6 on 2025-09-21 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_studentprofile_caste_studentprofile_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='aadhaar_number',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='admission_no',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='annual_income',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='blood_group',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='caste',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='cgpa',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='department',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='district',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='puc_percentage',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='religion',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='roll_number',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='signature',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='sslc_percentage',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='state',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='student_phone',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='taluk',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='university_reg_no',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='studentprofile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty')], default='student', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
