# Generated by Django 5.2.6 on 2025-09-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_studentprofile_department_studentprofile_roll_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyprofile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='roll_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='semester',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
