# Generated by Django 5.2.6 on 2025-09-22 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_facultyprofile_address_alter_studentprofile_roll_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='student_signatures/'),
        ),
    ]
